[package]
name = "mla-fuzz-afl"
version = "0.1.0"
authors = ["Camille Mougey <camille.mougey@ssi.gouv.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "0"
bincode = "~1.3"
serde = { version = "1", features = ["derive"] }
curve25519-parser = { path = "../curve25519-parser" }
mla = { path = "../mla" }
